### ISSUE TITLE
Clicking a thumbs up or down button causes the app to crash

### ISSUE THREAD

**Issue by beleslie** [WheresMyBus/android#16]
When I click on a thumbs up or down button on a forum page listing the alerts for a route or neighborhood, the app crashes and the following error is reported:

FATAL EXCEPTION: main
                  Process: com.wheresmybus, PID: 3478
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                      at com.wheresmybus.ThumbsUpListener.onClick(ThumbsUpListener.java:28)
                      at android.view.View.performClick(View.java:5610)
                      at android.view.View$PerformClick.run(View.java:22260)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by beleslie** [comment]
Fixed in https://github.com/WheresMyBus/android/commit/8e0a987bcbbe95fbdbdae0c217ca469ad6208fad

**Comment by beleslie** [comment]
The solution: I needed to get the root view of the view for the thumbs up or down button to change the number of thumbs up or down displayed beneath the button.
