### ISSUE TITLE
App crashes when click "Submit Alert" button on home page

### ISSUE THREAD

**Issue by beleslie** [WheresMyBus/android#4]
When I click the "Submit Alert" button on the home screen, the app crashes. A message appears asking if I want to start the app again.

**Comment by beleslie** [comment]
The issue is likely related to the fragment I am attempting to implement.

**Comment by beleslie** [comment]
FATAL EXCEPTION: main
                  Process: com.wheresmybus, PID: 2384
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wheresmybus/com.wheresmybus.SubmitAlertActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #133: Error inflating class fragment
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                   Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #133: Error inflating class fragment
                   Caused by: android.view.InflateException: Binary XML file line #133: Error inflating class fragment
                   Caused by: java.lang.RuntimeException: com.wheresmybus.SubmitAlertActivity@e8bbdae must implement OnFragmentInteractionListener
                      at com.wheresmybus.BusRouteAlertFragment.onAttach(BusRouteAlertFragment.java:83)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1043)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268)
                      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1370)
                      at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2415)
                      at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                      at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:376)
                      at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
                      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:75)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                      at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:414)
                      at android.app.Activity.setContentView(Activity.java:2414)
                      at com.wheresmybus.SubmitAlertActivity.onCreate(SubmitAlertActivity.java:28)
                      at android.app.Activity.performCreate(Activity.java:6664)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by beleslie** [comment]
Fixed in https://github.com/WheresMyBus/android/commit/61eebc424ac1d308e9640eb8e4e2c7c62514a5fb

**Comment by beleslie** [comment]
The solution: I implemented the onFragmentInteractionListener interface in SubmitAlertActivity
