### ISSUE TITLE
Controllers failing to get data from the database (BasicSystemTest failing)

### ISSUE THREAD

**Issue by bmartz** [WheresMyBus/android#7]
The WMBController getNeighborhoods method isn't returning any data, nor is the OBAController getRoutes method. In the emulator, this can be seen as empty route and neighborhood catalog screens, and an empty dropdown on the submit alert screen.

Output from the failing BasicSystemTest:
Started running tests
D/In getRoutesSynch:: java.net.UnknownHostException: Unable to resolve host "wheresmybus-api.herokuapp.com": No address associated with hostname
I/TestRunner: failed: sendRoutesRequestToAPI(com.wheresmybus.BasicSystemTest)
I/TestRunner: ----- begin exception -----
I/TestRunner: java.lang.AssertionError
                  at org.junit.Assert.fail(Assert.java:86)
                  at org.junit.Assert.assertTrue(Assert.java:41)
                  at org.junit.Assert.assertFalse(Assert.java:64)
                  at org.junit.Assert.assertFalse(Assert.java:74)
                  at com.wheresmybus.BasicSystemTest.sendRoutesRequestToAPI(BasicSystemTest.java:51)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runners.Suite.runChild(Suite.java:128)
                  at org.junit.runners.Suite.runChild(Suite.java:27)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                  at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                  at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                  at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
I/TestRunner: ----- end exception -----
I/TestRunner: finished: sendRoutesRequestToAPI(com.wheresmybus.BasicSystemTest)
I/MonitoringInstrumentation: Activities that are still in CREATED to STOPPED: 0
I/TestRunner: started: sendRequestToAPI(com.wheresmybus.BasicSystemTest)
I/MonitoringInstrumentation: Activities that are still in CREATED to STOPPED: 0
I/TestRunner: failed: sendRequestToAPI(com.wheresmybus.BasicSystemTest)
I/TestRunner: ----- begin exception -----
I/TestRunner: java.lang.IndexOutOfBoundsException: Invalid index 27, size is 0
                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                  at java.util.ArrayList.get(ArrayList.java:308)
                  at com.wheresmybus.BasicSystemTest.sendRequestToAPI(BasicSystemTest.java:37)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runners.Suite.runChild(Suite.java:128)
                  at org.junit.runners.Suite.runChild(Suite.java:27)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                  at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                  at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                  at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertFalse(Assert.java:64)
at org.junit.Assert.assertFalse(Assert.java:74)
at com.wheresmybus.BasicSystemTest.sendRoutesRequestToAPI(BasicSystemTest.java:51)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)

java.lang.IndexOutOfBoundsException: Invalid index 27, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at com.wheresmybus.BasicSystemTest.sendRequestToAPI(BasicSystemTest.java:37)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)

I/TestRunner: ----- end exception -----
I/TestRunner: finished: sendRequestToAPI(com.wheresmybus.BasicSystemTest)
I/MonitoringInstrumentation: Activities that are still in CREATED to STOPPED: 0
I/TestRunner: run finished: 2 tests, 2 failed, 0 ignored
Disconnected from the target VM, address: 'localhost:8647', transport: 'socket'
Tests ran to completion.

**Comment by bmartz** [comment]
Restarted Android Studio and everything's happy again (was only a problem on my machine)
